[package]
name = "Rust_Simulations"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam = "0.8.4"
parking_lot = "0.12.3"
anyhow = "1.0.88"
rand = "0.8.5"
chrono = "0.4.38"
scheduled-thread-pool = "0.2.7"
amiquip = "0.4.2"
tokio = { version = "1.40.0", features = ["full"] }